"""add fitness fields to health profile

Revision ID: 872d039ef1a4
Revises: 07a75a4773b7
Create Date: 2026-07-21 09:47:11.711601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872d039ef1a4'
down_revision: Union[str, Sequence[str], None] = '07a75a4773b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_profiles', sa.Column('fitness_goal', sa.String(length=100), nullable=True))
    op.add_column('health_profiles', sa.Column('activity_level', sa.String(length=100), nullable=True))
    op.add_column('health_profiles', sa.Column('training_experience', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_profiles', 'training_experience')
    op.drop_column('health_profiles', 'activity_level')
    op.drop_column('health_profiles', 'fitness_goal')
    # ### end Alembic commands ###
